services:
  app:
    container_name: viettrace-core
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - '5050:5050'
    volumes:
      - './logs:/app/logs'
    networks:
      - viettrace-network

networks:
  viettrace-network:
    driver: bridge
