include:
  - postgres/compose.postgres.yml
x-config: &config
  container_name: viettrace-core-api
  restart: unless-stopped
  ports:
    - '3000:3000'
  depends_on:
    viettrace-postgres:
      condition: service_healthy
      restart: true
  networks:
    - viettrace-core-network

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    <<: *config

  app-dev:
    build:
      context: ../
      dockerfile: Dockerfile.dev
    <<: *config
    profiles:
      - dev
