services:
  viettrace-vault:
    image: hashicorp/vault:1.20
    container_name: viettrace-vault
    restart: unless-stopped
    ports:
      - '8200:8200'
    environment:
      - VAULT_ADDR=${VAULT_ADDR:?error}
    volumes:
      - vault-data:/vault/file:rw
      - vault-logs:/vault/logs:rw
      - ./config.hcl:/vault/config/config.hcl:ro
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/config.hcl
    healthcheck:
      test: ['CMD', 'vault', 'status']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - viettrace-vault-network

volumes:
  vault-data:
    driver: local
  vault-logs:
    driver: local

networks:
  viettrace-vault-network:
    driver: bridge
